name: Deploy Dev branches

on:
  push:
    branches-ignore:
      - master
      - staging
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Install NPM dependencies
      run: npm install
    - name: Run tests
      run: sls invoke test
